theme: jekyll-theme-minimal
title: 450 Web-програмування
description: Конспекти лекцій та лабораторні роботи з дисципліни "Web-програмування" для IV курсу спеціальності 121 "Інженерія програмного забезпечення" ОКР "Фаховий молодший бакалавр" Херсонського політехнічного фахового коледжу Державного університету "Одеська політехніка"